app = "lasd-ride-along-bot"
primary_region = "iad"

[http_service]
auto_start_machines = true
auto_stop_machines = true
internal_port = 8_080
min_machines_running = 1

[[vm]]
cpus = 1
memory = "1gb"
memory_mb = 1_024